name: ci_cmake

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/cmake.yml"
      - "code-experiments/build/c/CMakeLists.txt"
      - "code-experiments/src/**.c"
      - "code-experiments/src/**.h"
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release, Debug]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build C amalgamation
      run: python ${{github.workspace}}/do.py amalgamate-c
    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/code-experiments/build/c/ -B build/ -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
    - name: Build
      run: cmake --build build/ --config ${{matrix.build_type}}
