name: ci_python

on:
  push:
    paths:
      - ".github/workflows/python.yml"
      - "code-experiments/build/python/*"
      - "code-experiments/src/**.c"
      - "code-experiments/src/**.h"
  pull_request:
    paths:
      - ".github/workflows/python.yml"
      - "code-experiments/build/python/*"
      - "code-experiments/src/**.c"
      - "code-experiments/src/**.h"

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.version}}
        cache: "pip"
    - run: pip install -r ${{github.workspace}}/code-experiments/build/python/requirements.txt
    - run: python ${{github.workspace}}/do.py verbose run-python --user and-test          
